WHENEVER SQLERROR EXIT SQL.SQLCODE;
-- Project-D Task 9.14 test seeds (idempotent; mirror of mysql/pg/mssql)
DROP USER IF EXISTS RO_USER CASCADE;
DROP USER IF EXISTS RW_USER CASCADE;
CREATE USER RO_USER IDENTIFIED BY ro_pw QUOTA UNLIMITED ON USERS;
GRANT CONNECT, CREATE SESSION TO RO_USER;
CREATE USER RW_USER IDENTIFIED BY rw_pw QUOTA UNLIMITED ON USERS;
GRANT CONNECT, CREATE SESSION, RESOURCE TO RW_USER;
GRANT CREATE PUBLIC SYNONYM TO RW_USER;
CONNECT RW_USER/rw_pw@localhost:1521/FREEPDB1
CREATE TABLE DEMO_ITEMS (ID NUMBER PRIMARY KEY, NAME VARCHAR2(100));
INSERT INTO DEMO_ITEMS VALUES (1,'alpha');
INSERT INTO DEMO_ITEMS VALUES (2,'bravo');
INSERT INTO DEMO_ITEMS VALUES (3,'charlie');
COMMIT;
GRANT SELECT ON RW_USER.DEMO_ITEMS TO RO_USER;
CREATE PUBLIC SYNONYM DEMO_ITEMS FOR RW_USER.DEMO_ITEMS;
EXIT
